### ISSUE TITLE
Node connection into neurons fails

### ISSUE THREAD

**Issue by celiasmith** [ctn-archive/nengo_spinnaker_2014#104]
This connection fails

```
    inhib = nengo.Node([0]) #inhibit motor output
    for ensemble in motor_ens.all_ensembles:
        nengo.Connection(inhib, ensemble.neurons, 
            transform=[[-3]] * ensemble.n_neurons)
```

whereas this works

```
    inhib = nengo.Node([0]) #inhibit motor output
    inhib_ens = nengo.Ensemble(100,1)
    for ensemble in motor_ens.all_ensembles:
        nengo.Connection(inhib_ens, ensemble.neurons, 
            transform=[[-3]] * ensemble.n_neurons)
    nengo.Connection(inhib, inhib_ens)
```

The error is:

```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/viz.py", line 129, in runner
    self.build()
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/viz.py", line 98, in build
    self.sim = backend.Simulator(self.model)
  File "/Users/celiasmi/Library/Python/2.7/lib/python/site-packages/nengo_spinnaker/simulator.py", line 97, in __init__
    self.netlist = self.model.make_netlist(self.max_steps or 0)
  File "/Users/celiasmi/Library/Python/2.7/lib/python/site-packages/nengo_spinnaker/builder/builder.py", line 328, in make_netlist
    self, *args, **kwargs
  File "/Users/celiasmi/Library/Python/2.7/lib/python/site-packages/nengo_spinnaker/operators/sdp_receiver.py", line 38, in make_vertices
    raise NotImplementedError
NotImplementedError
```

**Comment by mundya** [comment]
@neworderofjamie, were you seeing this as well?

**Comment by mundya** [comment]
Sorry, this should also be reported at project-rig/nengo_spinnaker.

**Comment by celiasmith** [comment]
Do you want me to copy the issue there?

**Comment by mundya** [comment]
I've done this one, but if you could the other please? Thank you!  We'll sort out repos soon.

**Comment by celiasmith** [comment]
Done :smile:

**Comment by mundya** [comment]
Thanks :)

**Comment by neworderofjamie** [comment]
Yes, this is just the error I was seeing - It's basically the same
connection pattern too! It looked to me like it was trying to make
n_neurons-wide connection through the sdp_receiver hence ending up with
more than 64 'dimensions'

**Comment by mundya** [comment]
Cool, I'm working on this now.
